Use Git Trees to get API definitions
JuliaCloud/AWS.jl pull request #208
Opened 2020-10-02 18:44 UTC by mattBrzezinski

Resolves: #207 

## Problem
We are currently using the GitHub [Get Repository Contents](https://developer.github.com/v3/repos/contents/#get-repository-content) API to get definitions from the [aws/aws-sdk-js/apis](https://github.com/aws/aws-sdk-js/tree/master/apis) directory.

This API request is limited in returning the first 1,000 objects in a directory. AWS has now pushed to 1,008 files in the `/apis/` directory. This results in us now not being able to generate definitions for certain services. In merging some of the auto-generation I only realized now I've removed the low-level wrapper for [XRay](https://github.com/JuliaCloud/AWS.jl/commit/49ac50843dfc8a1e5add23a9fa59ad6e3d6a5dd4#diff-b03ddd764d1b2745ba6d15cfb9c3d844L238) two days ago breaking the calls for that service.

## Solution
GitHub recommends using [Get A Tree](https://developer.github.com/v3/git/trees/#get-a-tree) API instead for retrieving `>1,000` files. According to [this](https://github.community/t/github-get-tree-api-limits-and-recursivity/1300/2) post in the GitHub community this API has a limit of `100,000` objects before the requests are truncated.

I don't expect the `aws-sdk-js` to reach that number any time soon (currently 1,008 files). Instead of handling the case of `truncated=True`, I decided to just throw an error. This way the GH Action for auto-generation will fail and we can handle it if we ever get there.

2020-10-02 18:51 UTC, mattBrzezinski commented on src/AWSMetadataUtilities.jl
> +        return JSON.parse(String(response.body), dicttype=OrderedDict)
```suggestion

        return JSON.parse(String(response.body), dicttype=OrderedDict)
```

2020-10-02 19:05 UTC, iamed2 requested changes

2020-10-02 19:05 UTC, iamed2 commented on src/AWSMetadataUtilities.jl
> +            throw(FileTruncated("There are more API files that GitHub can send."))
Maybe this? I think it should be clearer than what's written but I'm not attached to this suggestion
```suggestion
            throw(FileTruncated("GitHub API file limit exceeded"))
```

2020-10-02 19:05 UTC, iamed2 commented on src/AWSMetadataUtilities.jl
> +    headers = ["User-Agent" => "JuliaCloud/AWS.jl"]
This line should be back where it came from, since it's referenced early on

2020-10-02 19:05 UTC, iamed2 commented on src/AWSMetadataUtilities.jl
> +function _generate_low_level_definitions(services::AbstractArray)
```suggestion
function _generate_low_level_definitions(services::AbstractArray{<:AbstractDict})
```
Since we use the dict interface below we can require this.

2020-10-02 21:43 UTC, mattBrzezinski commented
I need to think about this some more. This solution is working but has two problems:

1) It's so slow needing multiple HTTP calls to get information, it went from around 1 minute to like 5 minutes and it doesn't even complete cause it's rate limited.
2) The rate limit is 60 requests, it burns through them, and if AWS ever updates a bunch of services at the same time it'll eat them all at once.

2020-10-02 21:48 UTC, iamed2 commented
What about:
1. Shallow-cloning the repo using git
2. Getting the source code from latest release (e.g. https://github.com/aws/aws-sdk-js/releases/tag/v2.766.0)

2020-10-02 21:52 UTC, mattBrzezinski commented
> What about:
> 
> 1. Shallow-cloning the repo using git
>    or
> 2. Getting the source code from latest release (e.g. https://github.com/aws/aws-sdk-js/releases/tag/v2.766.0)

I think we'll have to do something like that instead. I'll work on it this weekend when I have some time.

2020-10-06 20:08 UTC, iamed2 requested changes
Maybe add a new description of this PR in a PR comment so people aren't confused if they read this PR in the future?

2020-10-06 20:08 UTC, iamed2 commented on src/AWSMetadataUtilities.jl
> +        service_metadata = response["metadata"]
```suggestion
        service_blob = blob(repo_name, service["sha"]; auth=auth)
        service = JSON.parse(String(base64decode(service_blob.content)))
        service_metadata = service["metadata"]
```

line was too long, changed to match _generate_high_level_wrapper

2020-10-06 20:08 UTC, iamed2 commented on src/AWSMetadataUtilities.jl
> +function _get_function_parameters(input::String, shapes::AbstractDict)
```suggestion
function _get_function_parameters(input::String, shapes::AbstractDict{String})
```
doesn't hurt to match the docstring

2020-10-06 20:08 UTC, iamed2 commented on Project.toml
> +GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
Add a version in `[compat]` (at least v5 and then maybe older ones as well).

2020-10-06 22:02 UTC, mattBrzezinski commented
> Maybe add a new description of this PR in a PR comment so people aren't confused if they read this PR in the future?

Added an updated section on using GitHub.jl, and that the auth token is provided in the GH Action which is what we use for auto-generation.

2020-10-07 01:49 UTC, iamed2 approved these changes

2020-10-07 14:37 UTC, merged