Don't write failed retry streams to parent buffer in _http_request
JuliaCloud/AWS.jl pull request #516
Opened 2021-11-17 07:15 UTC by IanButterworth

I believe https://github.com/JuliaWeb/HTTP.jl/pull/781 is the proper fix needed for #515.
That PR introduces an EOFError throw if the http response stream has promised content via `Content-length` but hits `eof`.

The issue is rare and only in heavily concurrent operations, and the retry handling in AWS.jl is well set up to handle that

However, there was also an AWS.jl bug that this PR fixes, where each failed retry was being passed to the `response_stream`.

2021-11-17 11:11 UTC, ericphanson commented
> heavily concurrent operations

This is totally orthogonal but if you run into https://github.com/JuliaWeb/HTTP.jl/issues/517 style issues (which I certainly did), you might want to try the Downloads.jl based backend to use libcurl instead of HTTP.jl. `AWS.DEFAULT_BACKEND[] = AWS.DownloadsBackend()` (or on a per-request basis with `backend=…`).

2021-11-17 18:53 UTC, IanButterworth commented
HTTP v0.9.17 is out https://github.com/JuliaRegistries/General/pull/48956

2021-11-17 19:02 UTC, IanButterworth commented
Can someone run the CI please 🙏🏻

2021-11-17 19:07 UTC, mattBrzezinski commented
bors try

2021-11-17 19:53 UTC, IanButterworth commented
I assume the bors failure is something else?

2021-11-17 19:55 UTC, mattBrzezinski commented
bors try

2021-11-17 20:59 UTC, IanButterworth commented
@omus Matt recommended I check if you know what's up with bors here?

2021-11-17 21:03 UTC, omus commented
> @omus Matt recommended I check if you know what's up with bors here?

Ah, your move of `write(response_stream, buffer)` is the source of the problem. We need to write out the streamed data to `response_stream` during a failure otherwise the error is lost. That's exactly what this error is trying to communicate:

```
┌ Error: Internal Error: provided body is empty while the reported content-length is non-zero
└ @ AWS.AWSExceptions ~/work/AWS.jl/AWS.jl/src/AWSExceptions.jl:92
```

2021-11-17 21:07 UTC, omus commented
> However, there was also an AWS.jl bug that this PR fixes, where each failed retry was being passed to the `response_stream`.

To fix this you may need to make `buffer` outside of the retry block and have an outer `try`/`finally` which writes the final response to the `response_stream` (a test should be added for this).

A possible better solution could be to not have `HTTP.request` throw exceptions. You'd need to throw an exception on the last attempt though.

2021-11-17 21:20 UTC, omus commented
bors try

2021-11-17 21:46 UTC, IanButterworth commented
Great. Thanks @omus

2021-11-17 22:20 UTC, omus requested changes
I'd like to see a test for the `EOFError` behaviour. Otherwise these changes look good

2021-11-17 22:46 UTC, IanButterworth commented
Ok. I'm not familiar with the mocking system here. Could you point me to a similar test?

2021-11-18 11:15 UTC, ericphanson commented
bors try

2021-11-18 17:54 UTC, ericphanson commented
bors try

2021-11-18 19:06 UTC, IanButterworth commented
Sorry for the noise.. I'm assuming I can't run tests locally first

2021-11-18 19:23 UTC, ericphanson commented
I wonder if this will work to let you run CI yourself:

bors delegate+

2021-11-18 19:23 UTC, ericphanson commented
bors try

2021-11-18 19:33 UTC, IanButterworth commented
I manually commented out test code and got this to work in isolation locally

2021-11-18 21:23 UTC, ericphanson commented
bors try

2021-11-18 21:48 UTC, IanButterworth commented on test/issues.jl
> +                return HTTP.Response(200, "{\"Location\": \"us-east-1\"}")  # Made up region
Dead code/old comment
```suggestion
                return HTTP.Response(200, "{\"Location\": \"us-east-1\"}")
```

2021-11-19 15:51 UTC, IanButterworth commented
I think this PR still has an inconsistency between the HTTP and Downloads backends.
I looked into the Downloads behavior and it does throw, but because the Downloads backend doesn't use a sacrificial buffer, AWS doesn't prevent the incomplete stream from being passed to the output buffer

I expanded the tests to cover the Downloads backend, which now passes locally for the HTTP backend, and fails for the Downloads backend with:

```julia
issue 515: Test Failed at /Users/ian/Documents/GitHub/AWS.jl/test/issues.jl:188
  Expression: length(resp) == length(data)
   Evaluated: 199 == 100
```

Here's a lower level example of the behavior that passes
```julia
using HTTP, Sockets, Test, Downloads

function do_incomplete_server()
    server = Sockets.listen(ip"0.0.0.0", 8080)
    task = @async HTTP.listen("0.0.0.0", 8080; server=server) do http
        HTTP.setstatus(http, 200)
        HTTP.setheader(http, "Content-Length" => "64") # Promise 64 bytes...
        HTTP.startwrite(http)
        HTTP.write(http, rand(UInt8, 63)) # ...but only send 63 bytes.
        # Close the stream so that eof(stream) is true and the client isn't
        # waiting forever for the last byte.
        HTTP.close(http.stream)
    end
    return server, task
end

@testset "HTTP backend" begin
    server, task = do_incomplete_server()
    err = nothing
    io = Base.BufferStream()
    try
        HTTP.get("http://localhost:8080"; response_stream = io, retry=false)
    catch err
        @show err
    finally
        try; close(server); wait(task); catch; end # Shutdown
    end
    @test bytesavailable(io) == 63
    @test err isa HTTP.IOError
    @test err.e isa EOFError
end


@testset "Downloads backend" begin
    server, task = do_incomplete_server()
    err = nothing
    io = Base.BufferStream()
    try
        Downloads.request("http://localhost:8080"; output = io, throw = true)
    catch err
        @show err
    finally
        try; close(server); wait(task); catch; end # Shutdown
    end
    @test bytesavailable(io) == 63
    @test err isa RequestError
end
```

What's the right thing to do here? It seems the use of a sacrificial buffer is a patch.. so i'm not sure whether you'd want to add that to the Downloads backend to fix this?

2021-11-19 16:22 UTC, IanButterworth commented
I just pushed a proposed fix. Tests should pass now

2021-11-19 16:23 UTC, ericphanson commented
bors try

2021-11-19 17:14 UTC, ericphanson commented
bors try

2021-11-19 17:16 UTC, omus commented on src/utilities/downloads_backend.jl
> +    end
I think we have to use a sacrificial buffer if you require `seek` support as not all `IO` types support it.

2021-11-19 17:35 UTC, IanButterworth commented on src/utilities/downloads_backend.jl
> +    end
Ok. I reverted and added a sacrificial buffer. Although the previous tests passed, the approach was flawed as `read` was reading from the start, not the end of the `response_buffer` which happened to be fresh in the test case, but may not be in the real world

2021-11-19 18:42 UTC, ericphanson commented
bors try

2021-11-19 20:39 UTC, IanButterworth commented
Ok. I'm now happy with this. Sorry it took so many attempts.

As this PR found and fixed, both the HTTP and Downloads backends were broken for `S3.get_object` for fixed-length responses when the response was incomplete, but in different ways;
- HTTP gave the incomplete data without error
- Downloads included the output from failed attempts, so too much data

Both are quite insidious for multi-part large file handling.

It would be great to get this out. (We're currently pinned at 1.62)

2021-11-22 15:28 UTC, omus commented on src/utilities/downloads_backend.jl
> +                # EOFErrors indicate a broken connection, so don't pass the buffer forward
Comment isn't quite right as there's no interaction with an `EOFError` here. We should probably be more specific in the conditional here as `Downloads.RequestError` will be thrown for any non 2XX status

2021-11-22 15:28 UTC, omus commented on src/utilities/downloads_backend.jl
> +                # but only if no EOFError error because of a broken connection.
```suggestion
                # Transfer the contents of the `BufferStream` into `response_stream` variable
                # but only if no EOFError error because of a broken connection.
```

2021-11-22 15:28 UTC, omus commented on src/utilities/request.jl
>              # Transfer the contents of the `BufferStream` into `response_stream` variable.
```suggestion
            # Transfer the contents of the `BufferStream` into `response_stream` variable
```

2021-11-22 15:28 UTC, omus commented on test/issues.jl
> +    end
I'm not sure we have an existing test for this but it would be good to double check the behaviour when the final response is an error. In that case we would want the output to be included in the stream

2021-11-22 15:34 UTC, omus commented on test/issues.jl
> +    end
My concern here is that exceptions from AWS will not be captured appropriately resulting an AWS failure exceptions with no context provided to the user.

2021-11-23 02:40 UTC, IanButterworth commented on test/issues.jl
> +    end
The tests I added are at the `S3.get_object` endpoint, so I've just added a test that it throws when all attempts fail. There's no buffer to check at that level

2021-11-23 03:37 UTC, IanButterworth commented on test/issues.jl
> +    end
I can't figure out a tidy way to do something specifically only on the final `@repeat` retry. Unfortunately `finally` blocks are called each retry.

2021-11-23 21:10 UTC, IanButterworth commented on test/issues.jl
> +    end
I added manual retry tracking as `@repeat` didn't seem to expose a tidier way to do so

2021-11-23 21:12 UTC, IanButterworth commented
Could someone please bors try

If this PR requires further changes, I'd greatly appreciate code suggestions. I'm keen for this problem to be fixed and released.

2021-11-23 22:30 UTC, ericphanson commented
bors try

2021-11-24 15:05 UTC, omus commented
I'll be 

> If this PR requires further changes, I'd greatly appreciate code suggestions. I'm keen for this problem to be fixed and released.

I'll try to help push this along today

2021-11-24 15:53 UTC, omus commented on test/issues.jl
> +                        throw(Downloads.RequestError("", 18, "transfer closed with 1 bytes remaining to read", Downloads.Response("http", "", 200, "HTTP/1.1 200 OK", ["content-length" => "64"])))
I feel like I'm missing something.
```suggestion
                        throw(Downloads.RequestError("", 18, "transfer closed with 1 bytes remaining to read", Downloads.Response("http", "", 200, "HTTP/1.1 200 OK", ["content-length" => string(n)])))
```

2021-11-24 15:53 UTC, omus commented on test/issues.jl
> +            end
Avoid duplicating these patches. Something like this would allow you to generate the patches you need:
```julia
function _incomplete_patch(; data, max_attempts=4)
    attempt_num = 0
    n = length(data)

    patch = if AWS.DEFAULT_BACKEND[] isa AWS.HTTPBackend
        @patch function HTTP.request(args...; response_stream, kwargs...)
            attempt_num += 1
            if attempt_num <= max_attempts
                write(response_stream, data[1:n - 1]) # an incomplete stream that shouldn't be retained
                throw(HTTP.IOError(EOFError(), "msg"))
            else
                write(response_stream, data)
                return HTTP.Response(200, "{\"Location\": \"us-east-1\"}")
            end
        end
    elseif AWS.DEFAULT_BACKEND[] isa AWS.DownloadsBackend
        @patch function Downloads.request(args...; output, kwargs...)
            attempt_num += 1
            if attempt_num <= max_attempts
                write(output, data[1:n - 1]) # an incomplete stream that shouldn't be retained
                throw(Downloads.RequestError("", 18, "transfer closed with 1 bytes remaining to read", Downloads.Response("http", "", 200, "HTTP/1.1 200 OK", ["content-length" => string(n)])))
            else
                write(output, data)
                return Downloads.Response("http", "", 200, "HTTP/1.1 200 OK", ["content-length" => string(n))
            end
        end
    end

    return patch
end
```
Note: I added in the `string(n)` for content length and make a couple other tweaks

2021-11-24 15:53 UTC, omus commented on src/utilities/request.jl
> +    attempts = 4
More descriptive variable name:
```suggestion
    max_attempts = 4
```

2021-11-24 15:53 UTC, omus commented on src/utilities/request.jl
>          end
Although it's a bit more work I think we should probably switch the `@repeat try` and this one. That should result in less logic to maintain (I'm fine with doing this in a follow up PR if you prefer). Here's a quick demo of how that would work:
```julia
julia> function _request(io::IO, num_fails)
           i = 0
           local buffer
           try
               @repeat 4 try
                   i += 1
                   println("try: $i")
                   buffer = Base.BufferStream()
                   write(buffer, "data")
                   i < num_fails && error("retry")
               catch e
                  println("catch: $i")
                  @retry if e.msg == "retry" end
               end
           finally
               println("finally: $i")
               close(buffer)
               write(io, buffer)
           end
       end
_request (generic function with 1 method)

julia> function demo(num_fails)
           io = IOBuffer()
           try
               _request(io, num_fails)
           finally
               @show String(take!(io))
           end
       end
demo (generic function with 3 methods)

julia> demo(2)
try: 1
catch: 1
try: 2
finally: 2
String(take!(io)) = "data"
false

julia> demo(5)
try: 1
catch: 1
try: 2
catch: 2
try: 3
catch: 3
try: 4
catch: 4
finally: 4
String(take!(io)) = "data"
ERROR: retry
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] macro expansion
   @ ./REPL[33]:10 [inlined]
 [3] macro expansion
   @ ~/.julia/packages/Retry/vS1bg/src/repeat_try.jl:192 [inlined]
 [4] _request(io::IOBuffer, num_fails::Int64)
   @ Main ./REPL[33]:5
 [5] demo(num_fails::Int64)
   @ Main ./REPL[34]:4
 [6] top-level scope
   @ REPL[37]:1
```

2021-11-24 15:56 UTC, omus commented on test/issues.jl
> +            end
You can then use this via:
```julia
apply(_incomplete_patch(; data=data, max_attempts=2) do
    ...
end

apply(_incomplete_patch(; data=data, max_attempts=4) do
    ...
end

2021-11-24 16:35 UTC, IanButterworth commented
Thanks @omus I just pushed the easy suggestions. Feel free to push the bigger change here, or in a following PR, whichever you prefer

2021-11-24 16:38 UTC, ericphanson commented
bors try

2021-11-24 18:56 UTC, ericphanson commented
bors try

2021-11-24 20:17 UTC, IanButterworth commented
AWS was having a bad day, I think the error above is unrelated and cleared now
```
Load Credentials: Test Failed at /home/runner/work/AWS.jl/AWS.jl/test/AWSCredentials.jl:8
  Expression: e.code in [["AccessDenied", "EntityAlreadyExists"];]
   Evaluated: "400" in ["AccessDenied", "EntityAlreadyExists"]
Stacktrace:
 [1] top-level scope at /home/runner/work/AWS.jl/AWS.jl/test/AWSCredentials.jl:8
 [2] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Test/src/Test.jl:1107
 [3] top-level scope at /home/runner/work/AWS.jl/AWS.jl/test/AWSCredentials.jl:17
```

2021-11-24 20:28 UTC, omus commented on src/utilities/downloads_backend.jl
> +    attempts = 4
```suggestion
    max_attempts = 4
```

2021-11-24 20:28 UTC, omus commented on src/utilities/downloads_backend.jl
> +    @repeat attempts try
```suggestion
    @repeat max_attempts try
```

2021-11-24 20:28 UTC, omus commented on src/utilities/downloads_backend.jl
> +                if should_write || attempt == attempts
```suggestion
                if should_write || attempt == max_attempts
```

2021-11-24 20:28 UTC, omus commented on src/utilities/request.jl
> +    @repeat attempts try
```suggestion
    @repeat max_attempts try
```

2021-11-24 20:28 UTC, omus commented on src/utilities/request.jl
> +            if should_write || attempt == attempts
```suggestion
            if should_write || attempt == max_attempts
```

2021-11-24 20:30 UTC, omus approved these changes
I'm good with to proceed with these changes now. We can attempt https://github.com/JuliaCloud/AWS.jl/pull/516/files#r756212793 as a follow up

2021-11-24 20:30 UTC, omus commented
bors try

2021-11-25 17:25 UTC, omus commented
bors r+

2021-11-25 17:32 UTC, merged

2021-11-25 17:59 UTC, omus commented on src/utilities/request.jl
>          end
Working in this in https://github.com/JuliaCloud/AWS.jl/pull/522