WIP: Use Kwargs instead of Dict for optional parameters
JuliaCloud/AWS.jl pull request #518
Opened 2021-11-17 21:44 UTC by mattBrzezinski

2021-11-18 20:38 UTC, mattBrzezinski commented
bors try

2021-11-18 22:22 UTC, iamed2 commented on src/api_generation/high_level.jl
> +             MAPPING = $(aws_service_param_mapping)
```suggestion
             const MAPPING = $(aws_service_param_mapping)
```
You don't expect to reassign `MAPPING` right?

Also I think it could use a better name. MAPPING just indicates its type and not its contents.

2021-11-18 22:26 UTC, iamed2 commented on src/api_generation/utilities.jl
> +    # This is a mapping of Julia snake syntax to what AWS wants
Please tone down the aggression here.

2021-11-18 22:46 UTC, mattBrzezinski commented on src/api_generation/high_level.jl
> +             MAPPING = $(aws_service_param_mapping)
I've added a comment describing the relationship and kept the same name. I feel like that's better than something more lengthy like `const JULIA_TO_AWS_SYNTAX_MAPPING`?

2021-11-18 23:12 UTC, iamed2 reviewed
I think we should use the PascalCase form from the specs for the kwargs, like boto3 does. If we do that, we can be reasonably sure we won't get collisions between our special kwargs and AWS parameters.

2021-11-18 23:12 UTC, iamed2 commented on src/api_generation/utilities.jl
> +        "s3" => Dict("body" => "body"), "ec2" => Dict("client_token" => "ClientToken")
IIUC, the S3 thing is different than EC2 and it's just another mechanism that we haven't yet considered. The fact that `"body"` is a parameter we pass through is entirely due to us [hard-coding](https://github.com/JuliaCloud/AWS.jl/blob/57696ba9a34dfff75f4c0dea3e42cba4c92e7001/src/AWS.jl#L263) special behaviour for the RestXMLService. 

They include the `"payload"` parameter in the service description which describes what gets put in the HTTP request body. So a conforming solution for S3 would be something like (pseudocode):

```julia
if "payload" in keys(endpoint)
    http_body = pop!(params, endpoint["payload"])
end
```

This appears to be the case for a number of services. 

*However*, the above is only correct for simple `"shape"`s. And in the majority of cases, the `"shape"` is of `"type": "structure"`. In that case we're actually supposed to pass a dictionary-like structure, and we don't want to strip off the key, we just want to do a normal `locationName` translation. This applies to endpoints like `CreateCloudFrontOriginAccessIdentityRequest` in `cloudfront-2018-11-05`. It would be interesting to see if that endpoint just breaks with our current system due to us hardcoding `body` as the source for `Request`'s `content` argument. 

---
All that to say I think it's valid to special case S3 here for now, but we should not consider it an inconsistency since it's really just something we're not handling properly yet. And we should also change the input argument name to `"Body"` to match both the spec and Boto3.

2021-11-18 23:15 UTC, iamed2 commented on src/api_generation/high_level.jl
> +             MAPPING = $(aws_service_param_mapping)
`const PARAMETER_MAPPING` would be better I think. Just any word describing what is being mapped. Having a comment in addition is also good though.

2021-11-19 12:35 UTC, oxinabox commented
> This is a breaking change and would require the tagging of AWS@2.0.0. The changes here modify how optional parameters are passed into requests. Currently users would need to do;


Can't we keep the old way as well and just deprecate it?

2021-11-19 12:39 UTC, oxinabox commented on src/api_generation/high_level.jl
> +                "$function_name is using a new protocol; $protocol which is not supported."
I am not sure the word "new" should be here.
since someone might for example be using this code many years after the protocol was added.
(say they were pinned to an old version for some reason)

idk maybe
```suggestion
                "$function_name is using an unexpected protocol; $protocol which is not supported."
```

2021-11-19 12:41 UTC, oxinabox commented on src/api_generation/utilities.jl
> +    # https://github.com/aws/aws-sdk-js/issues/3892
This link should be next to the particular mapping it is about.

2021-11-19 12:47 UTC, ericphanson reviewed
Cool! I like the explicit `MAPPING` approach and that the keyword arguments show up in the docstrings, and `snake_case` looks pretty reasonable for the few that I spot-checked. I haven't read enough of the discussion about inconsistencies/locationNames/shapes etc to understand/comment on that stuff (although I think it's pretty important).

2021-11-19 12:47 UTC, ericphanson commented on src/AWS.jl
> +    end
I think `.first` and `.second` is accessing the internal fields, so I'd do
```suggestion
    for (k, v) in kwargs
        str = string(k)
        _key = if haskey(mapping, str)
            mapping[str]
        else
            str
        end

        new_kwargs[string(_key)] = v
    end
```

2021-11-19 12:47 UTC, ericphanson commented on src/api_generation/high_level.jl
> +                "$function_name is using a new protocol; $protocol which is not supported."
```suggestion
                "$function_name is using a new protocol $protocol which is not supported."
```

2021-11-19 12:47 UTC, ericphanson commented on src/api_generation/high_level.jl
> +                Optional parameters can be passed as a keyword argument. Valid keys are:
```suggestion
                Optional parameters can be passed as a keyword argument. Valid keyword arguments are:
```

2021-11-19 12:49 UTC, ericphanson commented
Re- breakingness, we can probably use @omus's `FeatureSet` construction to make it opt-in: https://github.com/JuliaCloud/AWS.jl/blob/57696ba9a34dfff75f4c0dea3e42cba4c92e7001/src/AWS.jl#L47-L62

2021-11-19 12:52 UTC, oxinabox commented on src/AWS.jl
> +        new_kwargs[string(_key)] = kwarg.second
I don't think  `(::Pair).first` and `(::Pair).second` is part of the public API -- fields generally are not.
Would it be clearer if we used iterator destructuring to put them in variables?
idk if `k` and `v` are the best names -- all the names here are unclear to me.
I don't really now what this function is doing.

Also perhaps clearer tpo use `get` with default
```suggestion
    for (k, v) in kwargs
        str = string(k)
        _key = get(mapping, str, str)
        new_kwargs[string(_key)] = v
```

2021-11-19 12:53 UTC, oxinabox commented
(My comments are pretty throw away, just making them in passing. I haven't reviewed this properly, and will leave that to people who understand the package)

2021-11-19 13:35 UTC, oxinabox commented on src/services/athena.jl
> +MAPPING = Dict(
These should be generated as `const`

We also might want co consider generating them as 
`LittleDict` that are backed by tuples, for maximum speed.
But this is not going to be the performance critical part anyway.

2021-11-19 13:46 UTC, oxinabox commented on src/api_generation/high_level.jl
>              )
I think we might want to think about pulling this section out into it's own function.
Such that above rather than having
```julia
aws_service_param_mapping, operations = _generate_high_level_definitions(
    service_name, protocol, operations, shapes
)
```
we have
```julia
service_details = high_level_service_details(service_name, protocol, operations, shapes)
operations = _generate_operations(service_details)
aws_service_param_mapping = _aws_param_names!(service_name, service_details)
```

I am not sure though.
Multiple return values feels like a little bit of a codesmell of a function that is doing too much.
but maybe it is doing one thing, it is just that that one thing is best expresed as two things.

2021-11-19 14:31 UTC, mattBrzezinski commented
> > This is a breaking change and would require the tagging of AWS@2.0.0. The changes here modify how optional parameters are passed into requests.
> 
> Can't we keep the old way as well and just deprecate it?

Yes we definitely can just add this in as another function that is callable for each of the services operations! Probably the path of least resistance.

2021-11-19 14:31 UTC, mattBrzezinski commented on src/services/athena.jl
> +MAPPING = Dict(
Oops @iamed2 suggested this, I just have not regenerated the code for the service files.

2021-11-19 14:33 UTC, mattBrzezinski commented on src/api_generation/utilities.jl
> +    # https://github.com/aws/aws-sdk-js/issues/3892
I left it above as I'm not sure if this is currently limited to just EC2, I have a suspect that it is possibly more wide-spread but need to confirm.

2021-11-19 16:14 UTC, iamed2 commented on src/api_generation/utilities.jl
> +    # https://github.com/aws/aws-sdk-js/issues/3892
@mattBrzezinski My hunch is that the particular issue you filed is unique to EC2. I think this because it's the only service with a unique protocol. Using grep to grab protocols:

```
ericdavies@rutter ~/r/aws-sdk-js (master)> grep --no-filename -r \"protocol\"\:\ \" apis | cut -d\" -f4 | sort | uniq
ec2
json
query
rest-json
rest-xml
```

I suspect this case is "technically correct" because they've internally defined the EC2 protocol as "like query, but with weird capitalization".

2021-11-19 16:15 UTC, iamed2 commented on src/services/athena.jl
> +MAPPING = Dict(
I think LittleDict is also a good idea

2021-11-19 16:16 UTC, mattBrzezinski commented on src/api_generation/utilities.jl
> +    # https://github.com/aws/aws-sdk-js/issues/3892
Yes that's true that EC2 has it's own protocol. I'll dig around more later today to see if I can find more examples of these inconsistencies.

I'm sure botocore would also have these hard-coded workarounds as well.

2021-11-19 16:18 UTC, iamed2 commented
> > > This is a breaking change and would require the tagging of AWS@2.0.0. The changes here modify how optional parameters are passed into requests.
> > 
> > 
> > Can't we keep the old way as well and just deprecate it?
> 
> Yes we definitely can just add this in as another function that is callable for each of the services operations! Probably the path of least resistance.

Maybe a kwarg to `@service` or something? Another benefit to having `@service` is people can upgrade independently.

2021-11-19 17:47 UTC, omus requested changes
Very promising. A few more iterations are needed yet.
- Be

2021-11-19 17:47 UTC, omus commented on src/api_generation/high_level.jl
> +struct RestBased <: OperationType end
```suggestion
struct RESTBased <: OperationType end
```

2021-11-19 17:47 UTC, omus commented on src/api_generation/high_level.jl
> +        protocol::RestBased,
Seems like we don't really need an instance at all can just do 
```suggestion
        protocol::Type{RestBased},
```

2021-11-19 17:47 UTC, omus commented on src/api_generation/high_level.jl
> +             const MAPPING = $(aws_service_param_mapping)
```suggestion
             const SERVICE_PARAMETER_MAP = $(aws_service_param_mapping)
```

2021-11-19 17:47 UTC, omus commented on src/services/accessanalyzer.jl
> +                    "client_token" => string(uuid4()),
❗ As `params` has already been "amazonified" this should be "clientToken" and not "client_token". Looks like something is wrong in the code generation

2021-11-19 17:47 UTC, omus commented on src/services/accessanalyzer.jl
>  - `"tags"`: The tags to apply to the analyzer.
Should be rendered as:
```
# Keyword Parameters
- `archiveRules`: Specifies the archive rules to add for the analyzer. Archive rules
Optional parameters can be passed as a keyword argument. Valid keys are:
- `archive_rules`: Specifies the archive rules to add for the analyzer. Archive rules
  automatically archive findings that meet the criteria you define for the rule.
- `clientToken`: A client token.
- `tags`: The tags to apply to the analyzer.
```
We definitely don't need quotes around the keywords and the preface is no longer needed

2021-11-19 17:47 UTC, omus commented on src/api_generation/high_level.jl
>                  # Optional Parameters
```suggestion
                # Keyword Parameters
```

2021-11-19 17:47 UTC, omus commented on src/api_generation/high_level.jl
> +                Optional parameters can be passed as a keyword argument. Valid keys are:
Preface is no longer needed as these are just standard keywords and don't really need to be explained this much:
```suggestion
```

2021-11-19 17:47 UTC, omus commented on test/AWS.jl
> +            Secrets_Manager.delete_secret(secret_name; force_delete_without_recovery="true")
What happens if we pass in a `Bool` here?

2021-11-19 17:47 UTC, omus commented on test/AWS.jl
> +            S3.put_object(bucket_name, file_name; body=body)
Consider doing:
```suggestion
            @compat S3.put_object(bucket_name, file_name; body)
```

2021-11-19 17:47 UTC, omus commented on test/AWS.jl
> +                Glacier.add_tags_to_vault("-", vault; Tags=tags)
Appears this is set incorrectly according to the glacier mapping:
```suggestion
                Glacier.add_tags_to_vault("-", vault; tags=tags)
```

2021-11-19 17:47 UTC, omus commented on test/AWS.jl
> +                Glacier.add_tags_to_vault("-", vault; Tags=tags)
If this isn't failing we should probably investigate why... Thinking about it more it's because `amazonify` just translates names and doesn't cause a failure if you use the actual names used in the `params` dict. I don't think we should support both and should fail if a key is provided that isn't in the mapping

2021-11-19 17:49 UTC, omus commented on src/api_generation/high_level.jl
> +             MAPPING = $(aws_service_param_mapping)
I like `SERVICE_PARAMETER_MAP`. It doesn't matter much if it's wordy

2021-11-19 20:46 UTC, iamed2 commented on src/api_generation/high_level.jl
> +        protocol::RestBased,
Instances are better for the compiler and easier to read.

2021-11-19 20:49 UTC, iamed2 commented
I want to make sure this gets discussed and not buried under suggestions so I'm just going to copy and paste:

I think we should use the PascalCase form from the specs for the kwargs, like boto3 does. If we do that, we can be reasonably sure we won't get collisions between our special kwargs and AWS parameters.

2021-11-22 15:52 UTC, mattBrzezinski commented on src/api_generation/high_level.jl
> +                "$function_name is using a new protocol; $protocol which is not supported."
This is used for generating high-level APIs. End users shouldn't care for this, as it only matters for maintainers of this package.

2021-11-22 17:19 UTC, mattBrzezinski commented on test/AWS.jl
> +                Glacier.add_tags_to_vault("-", vault; Tags=tags)
In the couple of lines above we were passing in,

> tags = Dict("Tags" => LittleDict("Tag-01" => "Tag-01", "Tag-02" => "Tag-02"))

This worked well because Glacier was expecting `Tags` at the top-level value in the structure. Now however since we're using snake_case kwargs we have a translation inside of `src/services/glacier.jl` that specifies,

> tags => Tags

So we need to pass in this structure as `tags=tags`, this will then convert the high-level object to `Tags` and continue along as it previously worked when making the request.

2021-11-22 17:20 UTC, mattBrzezinski commented on test/AWS.jl
> +                Glacier.add_tags_to_vault("-", vault; Tags=tags)
@iamed2 This is another example of inconsistencies in the operation definitions. Every other Glacier optional parameter is specified in camel case EXCEPT for `Tags`.

```julia
"part_size" => "x-amz-part-size",
"job_parameters" => "jobParameters",
"archive_size" => "x-amz-archive-size",
"checksum" => "x-amz-sha256-tree-hash",
"range" => "Range",
"completed" => "completed",
"archive_description" => "x-amz-archive-description",
"body" => "body",
"policy" => "policy",
"vault_notification_config" => "vaultNotificationConfig",
"tag_keys" => "TagKeys",
"statuscode" => "statuscode",
"marker" => "marker",
"tags" => "Tags",
"limit" => "limit",
```

2021-11-22 17:31 UTC, mattBrzezinski commented on test/AWS.jl
> +            Secrets_Manager.delete_secret(secret_name; force_delete_without_recovery="true")
Works both ways! I don't have an example off hand but I did remember times where requests would fail for certain services.

I remember passing in a `string(1)` or `1` and it failed and it needed to be the opposite type. I can set this as a `Bool` going forward, but things *can* be finicky.

2021-11-22 17:36 UTC, iamed2 commented on test/AWS.jl
> +                Glacier.add_tags_to_vault("-", vault; Tags=tags)
Sure but in this case the difference is clearly communicated in the service spec, and there's nothing special necessary to handle this case as it follows the standard `rest-json` protocol.

2021-11-22 17:39 UTC, mattBrzezinski commented on test/AWS.jl
> +                Glacier.add_tags_to_vault("-", vault; Tags=tags)
Correct, but in the current implementation in this package you as a user need to know that this specific parameter is the only one with a capitalization. If you make a request now you'll get some vague error back from AWS saying that the structure is malformed.

Going forward with these changes or like-wise ones, it's not a problem. But it's more-so to just highlight that there are inconsistencies all throughout the SDK, and it wouldn't surprise me if there's another service in a situation like EC2.

2021-11-22 17:59 UTC, iamed2 commented on test/AWS.jl
> +                Glacier.add_tags_to_vault("-", vault; Tags=tags)
> Correct, but in the current implementation in this package you as a user need to know that this specific parameter is the only one with a capitalization.

This is clear in the SDK docs though. I don't know how a user would expect to know what each argument is called without checking the docs. And it's consistent between boto3 and the PHP and JS SDKs, which both match how we pass arguments (as kwargs or a dict). The SDKs which are different (Go, C++, Ruby, Java) standardize casing across every type of service. The Ruby SDK is notably the only official SDK which passes a generic map of arguments AND standardizes casing.

2021-11-22 18:09 UTC, mattBrzezinski commented on test/AWS.jl
> +                Glacier.add_tags_to_vault("-", vault; Tags=tags)
I don't think it's a stretch to assume that if the parameter is `tags` for one service it would be that for another and not `Tags`.

My issue here is that all of these inconsistencies don't inspire confidence that this package will just work out of the box for every service.

2021-11-22 18:16 UTC, mattBrzezinski commented on test/AWS.jl
> +            Secrets_Manager.delete_secret(secret_name; force_delete_without_recovery="true")
Ah here's an example,

https://github.com/JuliaCloud/AWS.jl/blob/57696ba9a34dfff75f4c0dea3e42cba4c92e7001/test/AWS.jl#L961

2021-11-22 18:18 UTC, iamed2 commented on test/AWS.jl
> +                Glacier.add_tags_to_vault("-", vault; Tags=tags)
> My issue here is that all of these inconsistencies don't inspire confidence that this package will just work out of the box for every service.

But as we progress to implementing the specs more correctly, we make progress. So far there has been exactly one case (EC2) where the spec did not appear to match required behaviour. This glacier situation was an example of the package working perfectly. This PR changed what the API expected, and so we needed to change what the tests passed.

2021-12-07 19:39 UTC, mattBrzezinski commented
Coming back around to this, more though needs to be put in here... I was under the assumption that at a service level each optional parameter has the same mapping. 

In this example with S3. The `GetObjectRequest` has the optional parameter `VersionId` with a location name `verisonId`. However the `WriteGetObjectResponseRequest` has this as `x-amz-fwd-header-x-amz-version-id`.

I guess this can now become a function level? Quite sad.

2023-03-21 16:34 UTC, mattBrzezinski commented
Closing as this is lingering and not being addressed.

2023-03-21 16:34 UTC, closed without merging